//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] File_SevenZipDll {
            get {
                object obj = ResourceManager.GetObject("File_SevenZipDll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   キャンセル(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Cancel_A {
            get {
                return ResourceManager.GetString("String_Cancel_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pe インストーラ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Caption {
            get {
                return ResourceManager.GetString("String_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Close_A {
            get {
                return ResourceManager.GetString("String_Close_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール(&amp;I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Execute_Install_A {
            get {
                return ResourceManager.GetString("String_Execute_Install_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Execute_Start_A {
            get {
                return ResourceManager.GetString("String_Execute_Start_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在進捗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Label_CurrentProgress_A {
            get {
                return ResourceManager.GetString("String_Label_CurrentProgress_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Label_DirectoryPath_A {
            get {
                return ResourceManager.GetString("String_Label_DirectoryPath_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラットフォーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Label_Platform_A {
            get {
                return ResourceManager.GetString("String_Label_Platform_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクト(&amp;P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Label_Project_A {
            get {
                return ResourceManager.GetString("String_Label_Project_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全体進捗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Label_TotalProgress_A {
            get {
                return ResourceManager.GetString("String_Label_TotalProgress_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検証 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_LogKind_Debug {
            get {
                return ResourceManager.GetString("String_LogKind_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   委譲 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_LogKind_Error {
            get {
                return ResourceManager.GetString("String_LogKind_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_LogKind_Information {
            get {
                return ResourceManager.GetString("String_LogKind_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   些細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_LogKind_Trace {
            get {
                return ResourceManager.GetString("String_LogKind_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_LogKind_Warning {
            get {
                return ResourceManager.GetString("String_LogKind_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32bit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Platform_32bit {
            get {
                return ResourceManager.GetString("String_Platform_32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   64bit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_Platform_64bit {
            get {
                return ResourceManager.GetString("String_Platform_64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択...(&amp;D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String_SelectDirectoryPath_A {
            get {
                return ResourceManager.GetString("String_SelectDirectoryPath_A", resourceCulture);
            }
        }
    }
}
